package com.xw.ws.server;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2016-09-28T11:31:30.484+08:00
 * Generated source version: 3.1.4
 * 
 */
@WebServiceClient(name = "helloworldService", 
                  wsdlLocation = "http://localhost:8080/wsServer/helloService?wsdl",
                  targetNamespace = "http://server.ws.xw.com/") 
public class HelloworldService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://server.ws.xw.com/", "helloworldService");
    public final static QName HelloworldInterfacePort = new QName("http://server.ws.xw.com/", "helloworldInterfacePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/wsServer/helloService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(HelloworldService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/wsServer/helloService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public HelloworldService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public HelloworldService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloworldService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public HelloworldService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public HelloworldService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public HelloworldService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns HelloworldInterface
     */
    @WebEndpoint(name = "helloworldInterfacePort")
    public HelloworldInterface getHelloworldInterfacePort() {
        return super.getPort(HelloworldInterfacePort, HelloworldInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloworldInterface
     */
    @WebEndpoint(name = "helloworldInterfacePort")
    public HelloworldInterface getHelloworldInterfacePort(WebServiceFeature... features) {
        return super.getPort(HelloworldInterfacePort, HelloworldInterface.class, features);
    }

}
